// generated by stringer -output=string.go -type=EOF,RoutingControl,SOF; DO NOT EDIT

package fibrechannel

import "fmt"

const (
	_EOF_name_0 = "EOFnEOFt"
	_EOF_name_1 = "EOFrt"
	_EOF_name_2 = "EOFdt"
	_EOF_name_3 = "EOFni"
	_EOF_name_4 = "EOFdtiEOFrtiEOFa"
)

var (
	_EOF_index_0 = [...]uint8{0, 4, 8}
	_EOF_index_1 = [...]uint8{0, 5}
	_EOF_index_2 = [...]uint8{0, 5}
	_EOF_index_3 = [...]uint8{0, 5}
	_EOF_index_4 = [...]uint8{0, 6, 12, 16}
)

func (i EOF) String() string {
	switch {
	case 65 <= i && i <= 66:
		i -= 65
		return _EOF_name_0[_EOF_index_0[i]:_EOF_index_0[i+1]]
	case i == 68:
		return _EOF_name_1
	case i == 70:
		return _EOF_name_2
	case i == 73:
		return _EOF_name_3
	case 78 <= i && i <= 80:
		i -= 78
		return _EOF_name_4[_EOF_index_4[i]:_EOF_index_4[i+1]]
	default:
		return fmt.Sprintf("EOF(%d)", i)
	}
}

const _RoutingControl_name = "RoutingControlDeviceDataUncategorizedRoutingControlDeviceDataSolicitedDataRoutingControlDeviceDataUnsolicitiedControlRoutingControlDeviceDataSolicitedControlRoutingControlDeviceDataUnsolicitedDataRoutingControlDeviceDataDataDescriptorRoutingControlDeviceDataUnsolicitedCommandRoutingControlDeviceDataCommandStatus"

var _RoutingControl_index = [...]uint16{0, 37, 74, 117, 157, 196, 234, 276, 313}

func (i RoutingControl) String() string {
	if i >= RoutingControl(len(_RoutingControl_index)-1) {
		return fmt.Sprintf("RoutingControl(%d)", i)
	}
	return _RoutingControl_name[_RoutingControl_index[i]:_RoutingControl_index[i+1]]
}

const (
	_SOF_name_0 = "SOFfSOFi4"
	_SOF_name_1 = "SOFi2SOFi3"
	_SOF_name_2 = "SOFn4"
	_SOF_name_3 = "SOFn2SOFn3"
	_SOF_name_4 = "SOFc4"
)

var (
	_SOF_index_0 = [...]uint8{0, 4, 9}
	_SOF_index_1 = [...]uint8{0, 5, 10}
	_SOF_index_2 = [...]uint8{0, 5}
	_SOF_index_3 = [...]uint8{0, 5, 10}
	_SOF_index_4 = [...]uint8{0, 5}
)

func (i SOF) String() string {
	switch {
	case 40 <= i && i <= 41:
		i -= 40
		return _SOF_name_0[_SOF_index_0[i]:_SOF_index_0[i+1]]
	case 45 <= i && i <= 46:
		i -= 45
		return _SOF_name_1[_SOF_index_1[i]:_SOF_index_1[i+1]]
	case i == 49:
		return _SOF_name_2
	case 53 <= i && i <= 54:
		i -= 53
		return _SOF_name_3[_SOF_index_3[i]:_SOF_index_3[i+1]]
	case i == 57:
		return _SOF_name_4
	default:
		return fmt.Sprintf("SOF(%d)", i)
	}
}
