// generated by stringer -output=string.go -type=Operation; DO NOT EDIT

package fip

import "fmt"

const _Operation_name = "OperationReservedOperationDiscoverySolicitationOperationDiscoveryAdvertisementOperationVirtualLinkInstantiationRequestOperationVirtualLinkInstantiationReplyOperationKeepAliveOperationClearVirtualLinksOperationVLANRequestOperationVLANNotificationOperationVendorSpecific"

var _Operation_index = [...]uint16{0, 17, 47, 78, 118, 156, 174, 200, 220, 245, 268}

func (i Operation) String() string {
	if i < 0 || i >= Operation(len(_Operation_index)-1) {
		return fmt.Sprintf("Operation(%d)", i)
	}
	return _Operation_name[_Operation_index[i]:_Operation_index[i+1]]
}
